dataset: "semantic_kitti"
save_dir: "ConvBKI_PC_02_V"
load_epoch: 1
map_method: "global"
visualize: False
meas_result: True
gen_preds: False
result_split: "val"
from_continuous: False
to_continuous: False
pred_path: "predictions_darknet"
train:
  B: 4
  num_epochs: 5
  lr: 0.007
  BETA1: 0.9
  BETA2: 0.999
  decayRate: 0.96
  remove_last: False
  opt: "Adam"
  grid_params:
    grid_size: [ 400.0, 400.0, 26.0 ]
    min_bound: [ -40.0, -40.0, -2.6 ]
    max_bound: [ 40.0, 40.0, 2.6 ]
test:
  grid_params:
    grid_size: [501.0, 501.0, 27.0]
    min_bound: [-50.1, -50.1, -2.7]
    max_bound: [50.1, 50.1, 2.7]
filter_size: 5
kernel: "sparse"
compound: False
per_class: True
ell: 0.5
seed: 42

num_frames: 10
num_workers: 10

debug_mode: False