num_classes: 15
data_dir: "/home/tigeriv/Data/Rellis-3D"
ignore_labels: = [0]
LABELS_REMAP:
  0: 0 #"void"
  1: 0 #"dirt"
  3: 1 #"grass"
  4: 2 #"tree"
  5: 3 #"pole"
  6: 4 #"water"
  7: 0 #"sky"
  8: 5 #"vehicle"
  9: 0 #"object"
  10: 0 #"asphalt"
  12: 0 #"building"
  15: 6 #"log"
  17: 7 #"person"
  18: 8 #"fence"
  19: 9 #"bush"
  23: 10 #"concrete"
  27: 11 #"barrier"
  31: 12 #"puddle"
  33: 13 #"mud"
  34: 14 #"rubble"
class_counts:
  0: 500
  1: 261005182
  2: 107172982
  3: 22852
  4: 224173
  5: 111345
  6: 554091
  7: 10626325
  8: 1588416
  9: 168764964
  10: 10944799
  11: 3502156
  12: 1493276
  13: 5798200
  14: 3395458
colors:
  0: [0, 0, 0]
  1: [0, 102, 0]
  2: [0, 255, 0]
  3: [0, 153, 153]
  4: [0, 128, 255]
  5: [255, 255, 0]
  6: [102, 0, 0]
  7: [204, 153, 255]
  8: [102, 0, 204]
  9: [255, 153, 204]
  10: [170, 170, 170]
  11: [41, 121, 255]
  12: [134, 255, 239]
  13: [99, 66, 34]
  14: [110, 22, 138]
